### ISSUE TITLE
unit tests - random error

### ISSUE THREAD

**Issue by btry** [pluginsGLPI/formcreator#1088]
**Describe the bug**
a unit test sometimes fails.

**To Reproduce**
Run tests on Travis, and cross your fingers. 

**Expected behavior**
green bar !

```
Failure (7 tests, 13/13 methods, 0 void method, 0 skipped method, 0 uncompleted method, 0 failure, 0 error, 1 exception)!
exceptions
> There is 1 exception:
=> tests\units\PluginFormcreatorTargetTicket::testUrgency():
==> An exception has been thrown in file /home/travis/build/pluginsGLPI/glpi/plugins/formcreator/tests/suite-integration/PluginFormcreatorTargetTicket.php on line 241:
==> RuntimeException: Toolbox::userErrorHandlerNormal() in /home/travis/build/pluginsGLPI/glpi/inc/toolbox.class.php line 657
==>   *** PHP Notice(8): Undefined index: tag
==>   Backtrace :
==>   inc/notificationeventmailing.class.php:159         
==>   inc/queuednotification.class.php:629               NotificationEventMailing::send()
==>   inc/commondbtm.class.php:1349                      QueuedNotification::forceSendFor()
==>   inc/document_item.class.php:172                    CommonDBTM->update()
==>   inc/commondbtm.class.php:1009                      Document_Item->post_addItem()
==>   plugins/formcreator/inc/targetbase.class.php:333   CommonDBTM->add()
==>   ...ins/formcreator/inc/targetticket.class.php:1320 PluginFormcreatorTargetBase->attachDocument()
==>   plugins/formcreator/inc/form_answer.class.php:1049 PluginFormcreatorTargetTicket->save()
==>   plugins/formcreator/inc/form_answer.class.php:762  PluginFormcreatorForm_Answer->generateTarget()
==>   plugins/formcreator/inc/form.class.php:1220        PluginFormcreatorForm_Answer->saveAnswers()
==>   ...tegration/PluginFormcreatorTargetTicket.php:241 PluginFormcreatorForm->saveForm()
==>   ...reator/vendor/atoum/atoum/classes/test.php:1363 tests\units\PluginFormcreatorTargetTicket->testUrgency()
==>   .../atoum/atoum/classes/test/engines/inline.php:43 mageekguy\atoum\test->runTestMethod()
==>   ...reator/vendor/atoum/atoum/classes/test.php:1918 mageekguy\atoum\test\engines\inline->run()
==>   ...reator/vendor/atoum/atoum/classes/test.php:1827 mageekguy\atoum\test->runEngine()
==>   ...reator/vendor/atoum/atoum/classes/test.php:1477 mageekguy\atoum\test->runEngines()
==>   ...eator/vendor/atoum/atoum/classes/runner.php:597 mageekguy\atoum\test->run()
==>   ...dor/atoum/atoum/classes/scripts/runner.php:1270 mageekguy\atoum\runner->run()
==>   ...eator/vendor/atoum/atoum/classes/script.php:281 mageekguy\atoum\scripts\runner->doRun()
==>   .../atoum/atoum/classes/script/configurable.php:80 mageekguy\atoum\script->run()
==>   ...ndor/atoum/atoum/classes/scripts/runner.php:214 mageekguy\atoum\script\configurable->run()
==>   ...ndor/atoum/atoum/classes/scripts/runner.php:702 mageekguy\atoum\scripts\runner->run()
==>   :                                                  mageekguy\atoum\scripts\runner::mageekguy\atoum\scripts\{closure}()
==>   in /home/travis/build/pluginsGLPI/glpi/inc/toolbox.class.php:438
==> Stack trace:
==> #0 /home/travis/build/pluginsGLPI/glpi/inc/toolbox.class.php(469): Toolbox::log(Object(Monolog\Logger), 400, Array)
==> #1 /home/travis/build/pluginsGLPI/glpi/inc/toolbox.class.php(657): Toolbox::logError('  *** PHP Notic...')
==> #2 /home/travis/build/pluginsGLPI/glpi/inc/notificationeventmailing.class.php(159): Toolbox::userErrorHandlerNormal(8, 'Undefined index...', '/home/travis/bu...', 159, Array)
==> #3 /home/travis/build/pluginsGLPI/glpi/inc/queuednotification.class.php(629): NotificationEventMailing::send(Array)
==> #4 /home/travis/build/pluginsGLPI/glpi/inc/commondbtm.class.php(1349): QueuedNotification::forceSendFor('Ticket', '1')
==> #5 /home/travis/build/pluginsGLPI/glpi/inc/document_item.class.php(172): CommonDBTM->update(Array)
==> #6 /home/travis/build/pluginsGLPI/glpi/inc/commondbtm.class.php(1009): Document_Item->post_addItem()
==> #7 /home/travis/build/pluginsGLPI/glpi/plugins/formcreator/inc/targetbase.class.php(333): CommonDBTM->add(Array)
==> #8 /home/travis/build/pluginsGLPI/glpi/plugins/formcreator/inc/targetticket.class.php(1320): PluginFormcreatorTargetBase->attachDocument('4', 'Ticket', '1')
==> #9 /home/travis/build/pluginsGLPI/glpi/plugins/formcreator/inc/form_answer.class.php(1049): PluginFormcreatorTargetTicket->save(Object(PluginFormcreatorForm_Answer))
==> #10 /home/travis/build/pluginsGLPI/glpi/plugins/formcreator/inc/form_answer.class.php(762): PluginFormcreatorForm_Answer->generateTarget()
==> #11 /home/travis/build/pluginsGLPI/glpi/plugins/formcreator/inc/form.class.php(1220): PluginFormcreatorForm_Answer->saveAnswers(Array)
==> #12 /home/travis/build/pluginsGLPI/glpi/plugins/formcreator/tests/suite-integration/PluginFormcreatorTargetTicket.php(241): PluginFormcreatorForm->saveForm(Array)
==> #13 /home/travis/build/pluginsGLPI/glpi/plugins/formcreator/vendor/atoum/atoum/classes/test.php(1363): tests\units\PluginFormcreatorTargetTicket->testUrgency()
==> #14 /home/travis/build/pluginsGLPI/glpi/plugins/formcreator/vendor/atoum/atoum/classes/test/engines/inline.php(43): mageekguy\atoum\test->runTestMethod('testUrgency')
==> #15 /home/travis/build/pluginsGLPI/glpi/plugins/formcreator/vendor/atoum/atoum/classes/test.php(1918): mageekguy\atoum\test\engines\inline->run(Object(tests\units\PluginFormcreatorTargetTicket))
==> #16 /home/travis/build/pluginsGLPI/glpi/plugins/formcreator/vendor/atoum/atoum/classes/test.php(1827): mageekguy\atoum\test->runEngine()
==> #17 /home/travis/build/pluginsGLPI/glpi/plugins/formcreator/vendor/atoum/atoum/classes/test.php(1477): mageekguy\atoum\test->runEngines()
==> #18 /home/travis/build/pluginsGLPI/glpi/plugins/formcreator/vendor/atoum/atoum/classes/runner.php(597): mageekguy\atoum\test->run()
==> #19 /home/travis/build/pluginsGLPI/glpi/plugins/formcreator/vendor/atoum/atoum/classes/scripts/runner.php(1270): mageekguy\atoum\runner->run(Array, Array, Array, Array)
==> #20 /home/travis/build/pluginsGLPI/glpi/plugins/formcreator/vendor/atoum/atoum/classes/script.php(281): mageekguy\atoum\scripts\runner->doRun()
==> #21 /home/travis/build/pluginsGLPI/glpi/plugins/formcreator/vendor/atoum/atoum/classes/script/configurable.php(80): mageekguy\atoum\script->run(Array)
==> #22 /home/travis/build/pluginsGLPI/glpi/plugins/formcreator/vendor/atoum/atoum/classes/scripts/runner.php(214): mageekguy\atoum\script\configurable->run(Array)
==> #23 /home/travis/build/pluginsGLPI/glpi/plugins/formcreator/vendor/atoum/atoum/classes/scripts/runner.php(702): mageekguy\atoum\scripts\runner->run()
==> #24 [internal function]: mageekguy\atoum\scripts\runner::mageekguy\atoum\scripts\{closure}()
==> #25 {main}
```

**Comment by btry** [comment]
i no longer reproduce.
